### ISSUE TITLE
Partial version numbers cause links

### ISSUE THREAD

**Issue by robbiet480** [skalavala/HassBot#4]
Say `.2` in a room. HassBot outputs `https://www.home-assistant.io/blog/posts/2/`. Why?

**Comment by robbiet480** [comment]
Credit to @ooii for finding this one

**Comment by ludeeus** [comment]
<https://github.com/skalavala/HassBot#default-command-is-lookup>

**Comment by skalavala** [comment]
I'm going to go ahead and close the issue... It is not an issue, it is a feature :)
